name: Update quantiles

on:
  repository_dispatch:
    types:
      - trigger_compute_quantiles
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.4'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
        python -m pip install -r requirements.txt

    - name: Run script
      env:
        DEV_BLOB_SAS: ${{ secrets.DEV_BLOB_SAS }}
        AZURE_DB_PW_DEV: ${{ secrets.AZURE_DB_PW_DEV }}
        AZURE_DB_PW_PROD: ${{ secrets.AZURE_DB_PW_PROD }}
        AZURE_DB_UID: ${{ secrets.AZURE_DB_UID_DEV }}

      run: |
        python pipelines/update_exposure_quantile.py
