name: Update exposure rasters

on:
  workflow_dispatch:
  schedule:
      - cron: "5 23 * * *" # 23:05 UTC, 5 minutes after ds-floodscan-ingest runs

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.4'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
        python -m pip install -r requirements.txt

    - name: Run script
      env:
        DEV_BLOB_SAS: ${{ secrets.DEV_BLOB_SAS }}
        PROD_BLOB_SAS: ${{ secrets.PROD_BLOB_SAS }}
        STAGE: ${{ vars.STAGE }}

      run: |
        python pipelines/update_exposure.py

    - name: Trigger raster stats pipeline
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/OCHA-DAP/ds-floodexposure-monitoring/dispatches \
          -d '{"event_type":"trigger_exposure_raster_stats"}'
