name: Update exposure raster stats

on:
  repository_dispatch:
    types:
      - trigger_exposure_raster_stats
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.4'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
        python -m pip install -r requirements.txt

    - name: Run script
      env:
        DEV_BLOB_SAS: ${{ secrets.DEV_BLOB_SAS }}
        AZURE_DB_PW_DEV: ${{ secrets.AZURE_DB_PW_DEV }}
        AZURE_DB_PW_PROD: ${{ secrets.AZURE_DB_PW_PROD }}
        AZURE_DB_UID: ${{ secrets.AZURE_DB_UID_DEV }}

      run: |
        python pipelines/update_raster_stats.py
        python pipelines/update_raster_stats_regions.py

    - name: Trigger quantile calculations
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/OCHA-DAP/ds-floodexposure-monitoring/dispatches \
          -d '{"event_type":"trigger_compute_quantiles"}'
